package com.webkorps.librarymanagement.model;

public class Student {
    private int membershipId;  // Auto-generated by the database
    private String name;
    private String email;
    private String role;
    private String password;

    // Default constructor
    public Student() {}

    // Parameterized constructor (excluding membershipId as it's auto-generated)
    public Student(String name, String email, String role, String password) {
        this.name = name;
        this.email = email;
        this.role = role;
        this.password = password;
    }

    // Getters and Setters
    public int getMembershipId() {
        return membershipId;
    }

    // No setter for membershipId since it's auto-generated
    public void setMembershipId(int membershipId) {
        this.membershipId = membershipId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // toString method
    @Override
    public String toString() {
        return "Student{" +
                "membershipId=" + membershipId +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", role='" + role + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

    
}
